spring:
  datasource:
    url: jdbc:mysql://localhost:3306/messagingapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Shaik@880
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
